### ISSUE TITLE
Bug in corrected Multiple inheritance example

### ISSUE THREAD

**Issue by quipa** [hankache/rakuguide#192]
In section 9.8 https://perl6intro.com/#_multiple_inheritance for the corrected example, I am not getting the right output. I am guessing the constructor is not correctly assigning the `lines-values`argument to the inherited `@.lines-values` attribute? 

Instead of:
```
Actual sales:
[10 9 11 8 7 10]
Forecast sales:
[9 8 10 7 6 9]
Actual vs Forecast:
[10 9 11 8 7 10]
[9 8 10 7 6 9]
```

I get:
```
Actual sales:
[10 9 11 8 7 10]
Forecast sales:
[9 8 10 7 6 9]
Actual vs Forecast:
[10 9 11 8 7 10]
[]
```

**Comment by hankache** [comment]
@quipa Thank you for your feedback. This seems like a regression in Rakudo. A bug has been submitted to fix it.

**Comment by Altai-man** [comment]
The issue was resolved, can this be closed? Now it outputs:
```
Actual sales:
[10 9 11 8 7 10]
Forecast sales:
[9 8 10 7 6 9]
Actual vs Forecast:
[10 9 11 8 7 10]
```
which is the same as what the guide claims?
